### ISSUE TITLE
Update Projects and Project Page

### ISSUE THREAD

**Issue by austinkocher** [Research-Basecamp/John-Torrens#11]
Projects. Each of these pages should link to something that John does. These are going to be usually very static, not much change over time. Here are the projects I want to highlight. 

1. Let's do one for the Ted Talk, one of the book, one for Sprout Social, one for "Vertical Companies" (cannabis company), and one for his teaching at Syracuse university. 
2. Currently the text says "Latest works. I shows only the best websites and portfolios built completely with passion, simplicity & creativity!" Let's change that to say "John's Projects." And the subtitle can say, "Explore John's portfolio of innovative projects, ventures, and achievements."

**Comment by Riwajchalise** [comment]
This one is incomplete because I am confused what should be the content for the pages @austinkocher
