### ISSUE TITLE
Update List of Pages and Add Resume Page

### ISSUE THREAD

**Issue by austinkocher** [Research-Basecamp/John-Torrens#12]
I think we need a page that says "Experience" or "Resume" or something, and I can fill in the text of his CV. He doesn't really have any publications, so we don't have to do that.

So our total pages should be: Home, About, Speaker Request, Resume, Projects, and News. (I'm not sure what to do with "News" right now, but let's just ignore it for now.)

**Comment by austinkocher** [comment]
Use this text for a sample on the resume page. I will add the rest of it later once we figure out the design.

# John M. Torrens, Ph.D.
(US) 110 Groman Dr. Sandy Creek, NY 13145
(Costa Rica) Nosara Ecological Estates Lote 26a, San Juan de Nosara, Guanacaste

## Syracuse Univesrity (Syracuse, NY)

## Professor of Entrepreneurial Practice, Deputy Department Chair, Program Manager of the MS in Entrepreneurship

Summary: Award winning professor in a top ranked entrepreneurship program. Teach/develop courses in the undergraduate, graduate, executive education, and on-line programs. Manage the full time and on-line programs of the MS Entrepreneurship.

- Increased applications to the MS Entrepreneurship by 400% between 2020 and 2023.
- Mentored teams with combined competition winnings of over $600,000
- Developed an executive education program for a patron in Saudi Arabia, worth over $1MM over 5 years.
- Developed and taught new classes on Founder/CEO Exits and Transitions, Entrepreneurial Deal Making, and
Entrepreneurship in the Cannabis Industry.
- Manage the undergraduate and graduate capstone business plan competitions.
- Manage the campus-wide Orange Tank Pitch Competition
- Led the task force to develop our NYC Center Strategy which launched in January 2020.
- Consistently high teaching evaluations over a 10-year period.
- Winner of the prestigious Meredith Teaching Award.
- Named Deputy Department Chair in 2018
- Curriculum lead on a $10MM SBA grant to develop and deliver the Boots2Business Curriculum, a 8-week online course and a 2-day workshop that teaches transitioning military service members Delivered to over 40,000 service members since 2013.

**Comment by Riwajchalise** [comment]
Should We have a different page for resume or are we linking the user's PDF file here. Lets discuss about this and then proceed.  @austinkocher

**Comment by austinkocher** [comment]
Yes, let's do a difference page called "Resume" for the resume, and we can link to the pdf as well.
