### ISSUE TITLE
Speaker Request Page - Adjust format of entire page as follows

### ISSUE THREAD

**Issue by austinkocher** [Research-Basecamp/John-Torrens#22]
Can we change the Speaker Request page to the following:

H1: Interested in booking Dr. Torrens to speak at your next event? Here's how.

John is an experienced speaker with a portfolio of presentations below that fit a wide variety of audiences. If you would like to bring John to your conference, business, or classroom guest lecture, contact him using the form below or book a 1-on-1 meeting directly with John using this link.

need a button that says "Click to Book Appointment with John" (Or just "Book Appointment"), Use this link: https://outlook.office.com/bookwithme/user/0850756ce9ac43f685c14d8a8928fb92%40syr.edu?anonymous&isanonymous=true

the email form

Put his photograph here but make it smaller, only the width of the text or slightly bigger so it doesn't take up so much space.

H2: Dr. Torrens' Portfolio of Workshops

Discover a range of sample workshops and presentations available from Dr. Torrens below. 

H3 "ADHD as an Entrepreneur’s Superpower"

**Description:** ADHD can be very debilitating condition, often resulting in undesirable business and life outcomes. However, in the context of entrepreneurship, certain types of ADHD have shown to be an incredible advantage if harnessed properly. In this session you will learn how to maximize the upside while minimizing the downside to allow your natural entrepreneurial abilities to shine.

H3 "Is your good idea a good business opportunity?"

**Description:** Many people have great ideas, but how do you know whether those ideas can be viable business opportunities. Learn a repeatable model to test your ideas for viability before you spend the time, energy, and money launching a business and bringing a product to market.

...etc below

**Comment by Riwajchalise** [comment]
What is the email form Is it the form we currently have?

**Comment by austinkocher** [comment]
Let's use John's email address for the form: jtorrens@syr.edu. 

Thanks, @Riwajchalise.
