### ISSUE TITLE
Homepage - adjust Ted Talk video alignment

### ISSUE THREAD

**Issue by austinkocher** [Research-Basecamp/John-Torrens#33]
Can we move the TED Talk to the left and adjust the text so that the video aligns better on the homepage? There are alignment issues on laptop and mobile.

![screenshot000763-1](https://github.com/user-attachments/assets/2021ef01-9bdd-4fe8-9149-c5b08114a31b)
![FBFACC47-F183-42B3-93AE-7662C87E5F5F_4_5005_c](https://github.com/user-attachments/assets/7bfa9ee2-b4ba-4eb8-863a-c5b526928b5b)

**Comment by Riwajchalise** [comment]
I am not exactly sure I tried resolving the issue and looks like this in my device. Do you mean padding between the text and videoshould be less looks like this in my device
![Screenshot 2024-07-24 at 9 47 28 PM](https://github.com/user-attachments/assets/e24200fa-139d-47dd-beb2-3708fbf3f1a7)
![viber_image_2024-07-24_21-48-32-053](https://github.com/user-attachments/assets/503ffdeb-4301-484c-8928-6fa9fd406274)

**Comment by Riwajchalise** [comment]
I will come back to this later
